[package]
name = "app"
version = "0.1.0"
edition = "2021"

[dependencies]
init_string_hash_map = { path = "../derive/init_string_hash_map" }
custom_model = { path = "../derive/custom_model" }
log_duration = { path = "../attribute/log_duration" }
